### ISSUE TITLE
Zoom events in an embedded viewport also scroll the surrounding page

### ISSUE THREAD

**Issue by craic** [arose/ngl#707]
I have a NGL viewport embedded in a long page.

When I zoom in/out of the structure in the viewport, the surrounding page scrolls.

I'm not clear on how to limit the mouse events to just the viewport - I see mentions elsewhere to using event.preventDefault but I don't understand how to include that in a basic     **document.addEventListener("DOMContentLoaded", function () {** block

I'm sure it is a simple fix but I'm not seeing it...

**Comment by arose** [comment]
Which version are you using? Should be fixed by https://github.com/arose/ngl/issues/636

**Comment by craic** [comment]
Ah !  I'm using the one in https://unpkg.com/ngl - and I know from another
experiment that this is not the latest

I'm using Chrome Version 78.0.3904.97 (Official Build) (64-bit) on Mac OS
Mojave 10.14.5

Just tried it with
https://cdn.rawgit.com/arose/ngl/v2.0.0-dev.32/dist/ngl.js - which I had
seen referenced somewhere - and the problem is still there

But if I use https://cdn.rawgit.com/arose/ngl/v2.0.0-dev.37/dist/ngl.js
 there is no problem !

I am really enjoying using NGL

thanks
